project:
  type: book

book:
  title: "Beispielsammlung"
  subtitle: "Komplettiert die Vorlesung Baudynamik"
  author: "Dr. Stephan Gollob & Pascal Gitz"
  date: "2023-08-02"
  date-format: full
  chapters:
    - index.qmd
    - part: "Rayleigh - Quotient"
      chapters:
        - rayleigh_01.ipynb
        - rayleigh_02.ipynb
        - rayleigh_03.ipynb
    - part: "Einmassenschwinger"
      chapters:
        - U2_EMS.ipynb
    - part: "Mehrmassenschwinger"
      chapters:
        - U3_MMS.ipynb
        - 3_MMS.ipynb
    - part: "Ersatzkraftverfahren"
      chapters:
        - U4_EKV.ipynb
    - references.qmd

bibliography: literatur_Beispielsammlung.bib

format:
  pdf:
    documentclass: scrreprt
    toc-depth: 2
    fig-pos: 'H'
    fig-format: svg
    lang: de
    execute:
      echo: false
      warning: false
    csl: apa-eu.csl
    link-citations: True
    tbl-colwidths: True

    include-in-header:
    - "packages_style.tex"
