project:
  type: book

book:
  title: "Beispielsammlung"
  subtitle: "Komplettiert die Vorlesung Baudynamik"
  author: "Dr. Stephan Gollob & Pascal Gitz"
  date: "2023-09-05"
  date-format: full
  chapters:
    - index.qmd
    - part: "Rayleigh-Quotient"
      chapters:
        - rayleigh_01.ipynb
        - rayleigh_02.ipynb
        - rayleigh_03.ipynb
    - part: "Einmassenschwinger"
      chapters:
        - ems_01.ipynb
        - ems_02.ipynb
        - ems_03.ipynb
        - ems_04.ipynb
        - ems_05.ipynb
        - ems_06.ipynb
        - ems_07.ipynb

    - part: "Mehrmassenschwinger"
      chapters:
        - mms_02.ipynb
        - mms_01.ipynb
        - mms_03.ipynb
        - mms_04.ipynb
        - mms_05.ipynb
        - mms_06.ipynb
    - part: "Ersatzkraftverfahren"
      chapters:
        - ekv_01.ipynb
        - ekv_02.ipynb
        - ekv_03.ipynb

    - references.qmd

bibliography: literatur_Beispielsammlung.bib

format:
  pdf:
    documentclass: scrreprt
    toc-depth: 2
    fig-pos: 'H'
    fig-format: svg
    lang: de
    execute:
      echo: false
      warning: false
    csl: apa-eu.csl
    link-citations: True
    tbl-colwidths: [50,50]
    include-in-header:
    - "packages_style.tex"
    
  html:
    fig-format: svg
    lang: de
    csl: apa-eu.csl
    link-citations: True
    tbl-colwidths: [50,50]

  docx:
    lang: de
    reference-doc: 'custom-reference.docx'

    execute:
      echo: false
      warning: false
    link-citations: True
    toc-depth: 2


