project:
  type: book

book:
  title: "Beispielsammlung"
  subtitle: "Komplettiert die Vorlesung Baudynamik"
  author: "Pascal Gitz & Dr. Stephan Gollob"
  date: "2023-08-02"
  date-format: full
  chapters:
    - index.qmd
    - U1_rayleigh.ipynb
    - U2_EMS.ipynb
    - U3_MMS.ipynb
    - references.qmd

bibliography: references.bib


format:
  pdf:
    documentclass: scrreprt
    toc-depth: 2
    fig-pos: 'H'
    fig-format: pdf
    lang: de
    execute:
      echo: false
      warning: false
