project:
  type: book

book:
  title: "Beispielsammlung"
  subtitle: "Komplettiert die Vorlesung Baudynamik"
  author: "Pascal Gitz & Dr. Stephan Gollob"
  date: "2023-08-02"
  date-format: full
  chapters:
    - index.qmd
    - U1_rayleigh.ipynb
    - U2_EMS.ipynb
    - U3_MMS.ipynb
    - U4_EKV.ipynb
    - references.qmd

bibliography: literatur_Beispielsammlung.bib

format:
  pdf:
    documentclass: scrreprt
    toc-depth: 2
    fig-pos: 'H'
    fig-format: svg
    lang: de
    execute:
      echo: false
      warning: false
    csl: apa-eu.csl
    link-citations: True
    tbl-colwidths: True
